### ISSUE TITLE
ignore_for_file: type=lint for generatedfile

### ISSUE THREAD

**Issue by mkbsugita** [realm/realm-dart#1289]
### Problem

generated file doesn't have `// ignore_for_file: type=lint`

### Solution

```
// ignore_for_file: type=lint

// **************************************************************************
// RealmObjectGenerator
// **************************************************************************
```

### How important is this improvement for you?

Dealbreaker

### Feature would mainly be used with

Local Database only

**Comment by nielsenko** [comment]
Why do you want to disable lints for the generated code?

Anyway, you can add your own `build.yaml` to add the line requested:
```yaml
targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - type=lint
```
