### ISSUE TITLE
Upgrade to newer flutter analyzer

### ISSUE THREAD

**Issue by brookman** [realm/realm-dart#1357]
### Problem

The current version realm_generator 1.3.0 depends on an older version of the Flutter analyzer package.
This version contains regressions which are fixed in analyzer 6.0.0. The new version makes ours code gen step 400% faster again.

### Solution

Upgrade the dependency.

### How important is this improvement for you?

Would be a major improvement

### Feature would mainly be used with

Local Database only

**Comment by desistefanova** [comment]
Hi @brookman!
Thanks for the reporting! We will definitely do that in some of the next releases. 
I hope it is not a blocker for you.

**Comment by nielsenko** [comment]
@brookman Are you using flutter master channel?

**Comment by nielsenko** [comment]
The following minimal `pubspec.yaml` illustrates the problem with your request:
```yaml
name: upgrade_analyzer
environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  analyzer: ^6.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any # no version of test will work with analyzer ^6.0.0 and current flutter stable (3.10.6)
```
You will not be able resolve this with current stable version of flutter. I think it is a bit unacceptable for a package like realm to require people to use the `master` channel or stop using the `test` package 😄 

That said, we will revisit on each new stable release of flutter.
