### ISSUE TITLE
After updating realm to 2.0, my dart_mappable objects with realm objects generate InvalidType now

### ISSUE THREAD

**Issue by ebelevics-midis** [realm/realm-dart#1600]
### What happened?

Before realm 2.0.0 (realm 1.6.0) I didn't recieve this issue, all models that included any realm objects did generate with no issues. Now I get errors and InvalidType. Other MappableClass objects that doesn't include realm object, generated with no issues.

As you have mentioned in changelog 'package:dart_mappable/dart_mappable.dart', I suppose I should start asking here.

### Repro steps

1. Create RealmObject in realm 2.0.0
2. Create other class (MappableClass) that has RealmObject included
3. Generate

### Version

Flutter 3.19.1/ Dart 3.3.0

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

Mac Sonoma 14.2

### Code snippets

```dart

// warehouse_dashboard_bloc.dart file
@MappableClass()
class WarehouseDashboardState with WarehouseDashboardStateMappable {
  Iterable<Warehouse> warehouses = const []; //Warehouse is RealmObject
  Warehouse? selectedWarehouse;

  bool get isAtWork => RoleSelectionBloc.instance.state_.isAtWork;
  User get user => MainBloc.instance.user!;
}

// warehouse_dashboard_bloc.mapper.dart file
  static Iterable<InvalidType> _$warehouses(WarehouseDashboardState v) =>
      v.warehouses;
  static const Field<WarehouseDashboardState, Iterable<InvalidType>>
      _f$warehouses = Field('warehouses', _$warehouses, mode: FieldMode.member);
  static InvalidType _$selectedWarehouse(WarehouseDashboardState v) =>
      v.selectedWarehouse;
  static const Field<WarehouseDashboardState, InvalidType>
      _f$selectedWarehouse =
      Field('selectedWarehouse', _$selectedWarehouse, mode: FieldMode.member);
```

### Stacktrace of the exception/crash you're getting

```shell
[SEVERE] realm:realm_generator on lib/data/warehouse/realm/warehouse.dart:
An error `FormatterException` occurred while formatting the generated source for
  `package:project/data/warehouse/realm/warehouse.dart`
which was output to
  `lib/data/warehouse/realm/warehouse.realm.dart`.
This may indicate an issue in the generator, the input source code, or in the
source formatter.
Could not format because the source could not be parsed:

line 45, column 8 of .: Expected an identifier.
   ╷
45 │ return switch (ejson) {
   │        ^^^^^^
   ╵
line 45, column 1 of .: Expected to find ';'.
   ╷
45 │ return switch (ejson) {
   │ ^^^^^^
   ╵
line 46, column 1 of .: Expected to find 'case'.
   ╷
46 │ {
   │ ^
   ╵
```

**Comment by fu89-team** [comment]
the same issue.

**Comment by nielsenko** [comment]
@ebelevics-midis Would you be comfortable sharing `package:project/data/warehouse/realm/warehouse.dart`?

Or can you create a minimal reproduction?

**Comment by ebelevics-midis** [comment]
I'll better create separate minimal project. After around 2-3 hours will reply.

**Comment by ebelevics-midis** [comment]
I did try to reproduce same issue with realm example, no luck. Did try add embedded objects, relationship... still couldn't replicate that problem

**Comment by jankuo** [comment]
here. i meet the same issue, after 4 hours , I  found it was  from flutter_links. just add 

```
analyzer:
  exclude: [your_path_of_model/**]
```

to  `analysis_options.yaml`

in my case is 

```
# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [lib/database/models/**]

linter:

  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
```
