### ISSUE TITLE
Realm SDK package version does not match the native library version (3.4.2 != 3.4.1).

### ISSUE THREAD

**Issue by Comanx** [realm/realm-dart#1831]
### What happened?

I encountered the version mismatch bug again (3.4.2 != 3.4.1). 
My APP database has encountered errors once more. After checking my pubspec.yaml, I confirmed that the Realm version is fixed at 3.4.1. However, after updating the lock file, realm_common was upgraded to 3.4.2. I suspect this is the cause of the bug, similar to issue #1788. I hope this issue can be fully addressed and fixed.

pubspec.yaml:
```
  realm: 3.4.1
```
pubspec.lock:
```
  realm:
    dependency: "direct main"
    description:
      name: realm
      sha256: f1bb19bfb7a498a17fafa0f5743f450093dc754024c1ef7e1370ce76162f19fe
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "3.4.1"
  realm_common:
    dependency: transitive
    description:
      name: realm_common
      sha256: "9efe3289f47f380c27b94fe8ad9abd1b31ffebf5a12d4853e66e06c317011bc6"
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "3.4.2"
  realm_dart:
    dependency: transitive
    description:
      name: realm_dart
      sha256: "1d214d80f307e96b70a5570de0bf185cda6ac8f3c6f8a86c023990220d4d5693"
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "3.4.2"
  realm_generator:
    dependency: transitive
    description:
      name: realm_generator
      sha256: d9c3b78fda398374049f8f225a4de89b1411f36ddd50b09c6132b6d769a72e6b
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "3.4.2"
```

### Repro steps

maybe
flutter upgrade
flutter build

### Version

3.27.4

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

3.4.1

### Stacktrace of the exception/crash you're getting

```shell

```

### Relevant log output

```shell

```
