### ISSUE TITLE
ETA 0.2.1

### ISSUE THREAD

**Issue by sebroehl** [realm/realm-dart#287]
Dear Realm-Team,

is there any ETA of the next version of this package, because I would like to use it in an app, but require the changes of #208 which are not included in version 0.2.0+alpha.

**Comment by nielsenko** [comment]
Hi @sebroehl

Thrilled to hear you plan on using realm! 

As you may have noticed #208 has been merged `master`. We would like to merge #270 as well, as before releasing, and due to some overdue vacations, this is unlikely to happen this week. However, it should happen soon. 

We try to keep `master` in a state where we can release at any time, so - if you feel adventurous - you may in the meantime take a git dependency on our `master` branch, fx by adding a dependency override in your `pubspec.yaml`:
```
dependency_overrides:
  realm:
    git:
      url: git@github.com:realm/realm-dart.git
      path: flutter/realm_flutter
      ref: master
```
Assuming you are using flutter, and not plain dart.

Otherwise, it is just around the corner.
